version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Pre-build phase

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-tasks-app .

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
